import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Footer from "../components/footer/footer";
import Navbar from "../components/navbar/navbar";
import Hero from "../components/hero/hero";
import About from "../components/about/about";

const Home = () => {
  return (
    <div>
      <Head>
        <title>Q. HEBERT | Photographe</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Navbar />
        <Hero />
        <About />
      </main>

      <Footer />
    </div>
  )
}

export default Home;