import styles from "../styles/Photos.module.css";
import Navbar from "../components/navbar/navbar";
import Gallery from "../components/gallery/gallery";
import Footer from "../components/footer/footer";
import Head from "next/head";

const Photos = () => {
	return (
		<div>
			<Head>
				<title>Q. HEBERT | Photographe</title>
				<meta name="description" content="Generated by create next app"/>
				<link rel="icon" href="/favicon.ico"/>
			</Head>

			<main className={styles.main}>
				<Navbar/>
				<Gallery/>
				<Footer/>
			</main>
		</div>
	);
}

export default Photos;